spring:
  kafka:
    bootstrap-servers: localhost:9092
    size: 2097152
    admin:
      enabled: true
    consumer:
      client-id: consumer-client
      group-id: consumer-group
      properties:
        allow.auto.create.topics: false
    producer:
      client-id: producer-client
azure:
  cosmos:
    uri: https://localhost:8081
    key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
    database: Boots
    container: Account
