server:
  port: 8082
service:
  logging-level: DEBUG

spring:
  kafka:
    size : 2097152
    username-path: ''
    password-path: ''
    bootstrap-servers: "pkc-4k99v.northeurope.azure.confluent.cloud:9092"
    client-id: eapi_testSuit_data
    consumer:
      auto-commit-interval-ms: 840000
      default-api-timeout-ms: 840000
      request-timeout-ms: 900000
      max-poll-interval-ms: 900000
      max.poll.records: 100
      concurrency: 100
      promotion:
        threads: 2
        topicName: dev-buk_eapi-testsuite-input-data
        outputTopic: dev-buk_eapi-testsuite-output-data
      group-id: eapi_testSuitInput_groupid012
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="{username}" password="{password}";
        mechanism: PLAIN
      security:
        protocol: SASL_SSL
      ssl:
        endpoint:
          identification:
            algorithm: https