spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      service:
        group-id: consumer-group
      client-id: test-client-group
      partition:
        outputTopic: dev-buk_eapi-partition-output-data
        group-id: cosmos_group
        topicName: outputTopic1
        function: cosmos
        partition-num: 3
    client-id: eapi_testSuit_data
    size: 2097152
azure:
  cosmos:
    uri: https://localhost:8081
    key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
    database: Boots
    container: Account
