spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      properties:
        allow.auto.create.topics: false
      service:
        group-id: consumer-group
      client-id: test-client-group
    client-id: eapi_testSuit_data
    size: 2097152
azure:
  cosmos:
    uri: https://localhost:8081
    key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
    database: Boots
    container: Account
